[api]
# Exposes /debug and /stats
address = ":5001"

[core]
# Use a specific cache implementation
cache_type = "internal"
# Use a specific db implementation
db_type = "bolt"
# Tune max go routines that can process blocks
# Defaults to (nproc * 3)
pool_size = 0

[redis]
dsn = "127.0.0.1:6379"

[chain]
ws_endpoint = "ws://localhost:8546"
rpc_endpoint = "http://localhost:8545"
# Defaults to Celo mainnet
chainid = 1337
# This will start a backfill if set to any other value
# Ideally this should remain 0
start_block = 0
batch_size = 100

[bootstrap]
# This will bootstrap the cache on which addresses to track
ge_registry = ["0x0f8E97ef2d6A42CF62549D4924FCBdcE83A1C6A5"]
watchlist = [""]
blacklist = [""]

[jetstream]
enable = true
endpoint = "nats://127.0.0.1:4222"
persist_duration_hrs = 48
