[api]
# Exposes /debug and /stats
address = ":5001"

[core]
# Use a specific cache implementation
cache_type = "redis"
# Use a specific db implementation
db_type = "bolt"
# Tune max go routines that can process blocks
# Defaults to (nproc * 3)
pool_size = 0
# If you are using an archive node, set this to true
batch_size = 100

[redis]
dsn = "127.0.0.1:6379"

[chain]
ws_endpoint = "ws://localhost:8546"
rpc_endpoint = "http://localhost:8545"
# Defaults to Celo mainnet
chainid = 1337
# This will start a backfill if set to any other value
# Ideally this should remain 0
start_block = 0

[bootstrap]
# This will bootstrap the cache on which addresses to track
ge_registries = ["0xE979a64D375F5D363d7cecF3c93B9aFD40Ba9f55"]
watchlist = ["0x14dc79964da2c08b23698b3d3cc7ca32193d9955"]
blacklist = [""]

[jetstream]
enable = true
endpoint = "nats://127.0.0.1:4222"
persist_duration_hrs = 48
